### ISSUE TITLE
Create the scanner

### ISSUE THREAD

**Issue by torisimon2** [cs481-ekh/s24-gone-phishin#100]
References #32

Implement a scanner for separating email contents in individual tokens/words 

Definition of Done:
- [x] When passed a string of text, the scanner is able to break it down into individual words
- [x] The scanner correctly handles any whitespace or special characters
- [x] The tokens are stored for making comparisons
- [x] The scanner is passed the email currently being viewed by the user

**Comment by SorrenMosher** [comment]
Attempted to refactor uiDisp.js script into multiple, but it seems there are issues with import/export in content scripts. More research will be needed: 
[https://stackoverflow.com/questions/48104433/how-to-import-es6-modules-in-content-script-for-chrome-extension/58137279#58137279](url)
Added the scanner.
Updated the extension to display the tokens rather than the email text.
[t:155]

**Comment by SorrenMosher** [comment]
Updated the scanner to handle whitespace and special characters correctly.
Wrote unit tests for the scanner, but had issues running them.
I am going to look into the testing issues and add them later.
[t:120]
