### ISSUE TITLE
Database timestamp for High Score

### ISSUE THREAD

**Issue by kdoster** [cs481-ekh/s24-gone-phishin#198]
When a score of 75% or higher is reached, a timestamp is pushed to the database.

**Comment by Subpoened-peon** [comment]
[t:35] Added another message system between uiDisp and dbHandler to timestamp when a high risk email is scanned. It currently timestamps whenever it is scanned, but since we aren't wanting to store any sort of user information, there didn't seem to be a simple solution for the database to recognize when an email had been scanned already. If we desire it to not timestamp emails that have already been scanned, we will look into it in the future.
